FROM node:alpine

ARG NPM_TOKEN 

RUN mkdir /web

WORKDIR /web

COPY .npmrc .npmrc

COPY package*.json ./

RUN echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > /web/.npmrc && \
    npm install && \
    rm -f /web/.npmrc

COPY . /web

CMD npm run start