version: "3.8"

networks:
  ordinly:

volumes:
  certbot-etc:
  certbot-var:
  web-root:

services:
  reverse-proxy:
    image: nginx:mainline-alpine
    volumes:
      - ../common/config/nginx/nginx.certbot.conf:/etc/nginx/nginx.conf
      - ../common/config/web-root:/var/www/html
      - ../common/config/certbot-etc:/etc/letsencrypt
      - ../common/config/certbot-var:/var/lib/letsencrypt
    ports:
      - 80:80

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../common/config/web-root:/var/www/html
      - ../common/config/certbot-etc:/etc/letsencrypt
      - ../common/config/certbot-var:/var/lib/letsencrypt
    depends_on:
      - reverse-proxy
    command: certonly --webroot --webroot-path=/var/www/html --email seanallanmackay@gmail.com --agree-tos --no-eff-email --force-renewal -d ordinly.com  -d www.ordinly.com
